[[pages]]
path = "FPS_neutralized.py"
name = "Neutralization Rate"
icon = "ğŸ "

[[pages]]
path = "FPS_graphs_boxplot.py"
name = "Boxplot"
icon = "ğŸ“Š"

[[pages]]
path = "FPS_graphs_choropleth.py"
name = "Choropleth Map"
icon = "ğŸ—ºï¸"

[[pages]]
path = "FPS_graphs_probit.py"
name = "Probit Model"
icon = "ğŸ“"